# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package definition and install dependencies
COPY package*.json ./
RUN npm install --ignore-scripts

# Copy the rest of the source code
COPY . .

# Build the project
RUN npm run build

# The server communicates over stdio, so no exposed ports are needed
CMD ["node", "build/index.js"]
